### ISSUE TITLE
[Bug] ML fails to load after the ZeresPluginLibrary update.

### ISSUE THREAD

**Issue by ScripterRickster** [Davilarek/MessageLoggerV2-fixed#10]
This issue started occurring on April 14th at around 6:40 PM EST after the ZeresPlugin had an issue with BDD after it updated. After the ZeresPlugin was updated, the message logger was still broken.

**Comment by Hermivore8151** [comment]
yep, i have the same issue

**Comment by CaptainStitches** [comment]
Same here, seems Discord changed some engine stuff again. Sadly there's no error printout to supply, just a toast that says the plugin failed to start.
![image](https://user-images.githubusercontent.com/8720757/232170062-db3a3cff-2b4d-4e38-88a6-8281fb70d5bd.png)

**Comment by Hacker1254** [comment]
its an easy fix
here is my edit (remove the .txt)

[MessageLoggerV2.plugin.js.txt](https://github.com/Davilarek/MessageLoggerV2-fixed/files/11238055/MessageLoggerV2.plugin.js.txt)

i found the error at line 3720
and added a null check to `.flat().find(obj => typeof obj.subscribe === 'function')?`

**Comment by CaptainStitches** [comment]
> its an easy fix here is my edit (remove the .txt)
> 
> [MessageLoggerV2.plugin.js.txt](https://github.com/Davilarek/MessageLoggerV2-fixed/files/11238055/MessageLoggerV2.plugin.js.txt)
> 
> i found the error at line 3720 and added a null check to `.flat().find(obj => typeof obj.subscribe === 'function')?`

You champion! Cheers friend!

**Comment by XxUnkn0wnxX** [comment]
yep fixed for me to, hope @Davilarek pushes this fix to the main repo..

**Comment by Hermivore8151** [comment]
> its an easy fix here is my edit (remove the .txt)
> 
> [MessageLoggerV2.plugin.js.txt](https://github.com/Davilarek/MessageLoggerV2-fixed/files/11238055/MessageLoggerV2.plugin.js.txt)
> 
> i found the error at line 3720 and added a null check to `.flat().find(obj => typeof obj.subscribe === 'function')?`

cheers bro, hope you have an awesome day :D

**Comment by Davilarek** [comment]
> its an easy fix here is my edit (remove the .txt)
> 
> [MessageLoggerV2.plugin.js.txt](https://github.com/Davilarek/MessageLoggerV2-fixed/files/11238055/MessageLoggerV2.plugin.js.txt)
> 
> i found the error at line 3720 and added a null check to `.flat().find(obj => typeof obj.subscribe === 'function')?`

Sorry, but your fix is wrong. It uses wrong `modalsApi` which *will* cause issues soon, I have found the fix and it'll be released soon.
Details: 
current `modalsApi` returns a list of Discord UI components (?)
![obraz](https://user-images.githubusercontent.com/62715937/232224799-5e2bb2ef-fc47-4aa8-b2f3-5370311bd2af.png)
but should return this:
![obraz](https://user-images.githubusercontent.com/62715937/232224867-fe87e6e1-7fca-42e0-90ad-480110c5479e.png)
the solution is to use the good one instead of the wrong, simple right?

**Comment by Davilarek** [comment]
for people asking "so what the @Hacker1254 's fix actually did?":
actually it prevented the error by checking if something the code tried to access was there or not.
## why I didn't do that myself?
because in a normal case it should just be there, but yeah I should add some if checks.
## why I didn't push his fix?
it wasn't a true fix. The real issue was some lines higher and since I fixed the real issue there was no need to use the "fake" fix.

real issue and fix location: https://github.com/Davilarek/MessageLoggerV2-fixed/blob/4131984c0cae47a7bdee1a9137e188bb62764024/Plugins/MessageLoggerV2/MessageLoggerV2.plugin.js#L3718

**Comment by Hacker1254** [comment]
i caused extra chaos lmao im sorry (also i don't really mess with BD plugins, i just provied a temp fix :3)

**Comment by Davilarek** [comment]
No, actually you bought me some time to make an actual fix, thanks 👍
